version: "3.8"
services:
  gogoyuedu-nestjs-api:
    container_name: gogoyuedu-nestjs-api
    build: .
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm install && npm run build && npm run start:prod"
    environment:
     - NODE_OPTIONS= --max_old_space-size=8192

  redis:
    image: redis:7-alpine
    env_file: ./.env
    restart: always
    command: sh -c 'redis-server --save 60 1 --loglevel warning --requirepass "$REDIS_PASSWORD"'
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
networks:
  default:
    external:
      name: docker-nginx-reverse-proxy_cmsnetwork
